[package]
name = "timely_container"
version = "0.12.0"
edition = "2018"
description = "Container abstractions for Timely"
license = "MIT"

[dependencies]
columnation = { version = "0.1" }
serde = { version = "1.0"}
